settings:
  kafka:
    producer:
      bootstrapServers:
        - localhost:9092
    consumer:
      waitingTimeInSeconds: 3
      topic: replicated_topic
      groupId: kafka-java-app
      autoOffsetReset: earliest #latest, earliest, none
      bootstrapServers:
        - localhost:9092

